### ISSUE TITLE
TypeError: required field "lineno" missing from alias

### ISSUE THREAD

**Issue by lucasldtdionatan** [efipay/sdk-python-apis-efi#1]
A versão fixada do pytest nessa lib está gerando alguns problemas para projetos mais recentes do django e ocasionando o erro do titulo acima.

A correção para este problema foi feito na [versão 6.2.5 ](https://docs.pytest.org/en/stable/changelog.html#pytest-6-2-5-2021-08-29)do pytest. Começamos a utilizar este novo sdk da efí recentemente depois de termos visto na documentação de desenvolvimento que o sdk gerencianet será descontinuado e depois te termos problemas no ambiente de produção para gerar os bolets. Mas feito essa mudança, nossos testes unitários do projeto pararam de funcionar, e não conseguimos atualizar a versão do pytest por conta da versão fixada nesta lib:

```
Because efipay (1.0.0) depends on pytest (6.2.3)
 and no versions of efipay match !=1.0.0, every version of efipay requires pytest (6.2.3).
So, because niwe-api depends on both efipay (*) and pytest (6.2.5), version solving failed.
```

desde já agradeço a atenção.
🙏

**Comment by pallomabritoGN** [comment]
Olá @lucasldtdionatan ! Tudo bem? 
Muito obrigada pelo report! Atualizamos o pytest na última release.
Seguimos à disposição caso possamos ajudar com algo mais.
Conte com a gente!

**Comment by palloma-brito-efi** [comment]
Olá @lucasldtdionatan ! Tudo bem?
Muito obrigada pelo report! Atualizamos o _pytest_ na última release.
Seguimos à disposição. Conte com a gente!
